exclude:
    - Gemfile
    - Gemfile.lock
    - tmp
# permalink: pretty

url: "https://hirgaz.org"

collections:
    games:
        output: true
        permalink: /:collection/:name

nav_pages:
    - games.html
    - about.html

title: Hirgaz Studios
# email: TODO
# twitter_username: TODO
github_username:  Hirgaz

# Build settings
markdown: kramdown
remote_theme: "jekyll/minima@1fe0fbf"
plugins:
    # - jekyll-feed

# TODO: Setup pagination.

minima:
    show_excerpts: true
    skin: classic
    hide_site_feed_link: true
    social_links:
        - title: Hirgaz Studios at Github
          icon: github
          url: "https://github.com/hirgaz"
